const $=selector=>document.querySelector(selector),config=window.DIENSTPLAN_CONFIG,supabaseClient=window.supabase.createClient(config.supabaseUrl,config.publishableKey),apiUrl=`${config.supabaseUrl}/functions/v1/${config.functionName}`;
const elements={login:$("#login"),loginForm:$("#login-form"),password:$("#password"),togglePassword:$("#toggle-password"),remember:$("#remember"),loginStatus:$("#login-status"),workspace:$("#workspace"),plans:$("#plans"),listStatus:$("#list-status"),search:$("#search"),sort:$("#sort"),logout:$("#logout"),forget:$("#forget"),openAdmin:$("#open-admin"),adminDialog:$("#admin-dialog"),adminLoginForm:$("#admin-login-form"),adminPassword:$("#admin-password"),toggleAdminPassword:$("#toggle-admin-password"),adminLoginStatus:$("#admin-login-status"),uploadDialog:$("#upload-dialog"),uploadForm:$("#upload-form"),planTitle:$("#plan-title"),planMonth:$("#plan-month"),planFile:$("#plan-file"),uploadStatus:$("#upload-status"),viewerDialog:$("#viewer-dialog"),viewerTitle:$("#viewer-title"),pdfViewer:$("#pdf-viewer")};
let plans=[],readerToken=sessionStorage.getItem("dienstplan-reader")||localStorage.getItem("dienstplan-reader")||"",adminToken=sessionStorage.getItem("dienstplan-admin")||"";
const monthFormatter=new Intl.DateTimeFormat("de-DE",{month:"long",year:"numeric",timeZone:"UTC"});

async function request(action,body={},token=readerToken){const response=await fetch(apiUrl,{method:"POST",headers:{"Content-Type":"application/json",apikey:config.publishableKey,...(token?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify({action,...body})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||"Die Anfrage konnte nicht ausgeführt werden.");return data}
function toggle(input,button){const visible=input.type==="text";input.type=visible?"password":"text";button.textContent=visible?"Anzeigen":"Ausblenden"}
function closeDialog(dialog){if(dialog.open)dialog.close();if(dialog===elements.viewerDialog){elements.pdfViewer.src="about:blank";elements.viewerTitle.textContent="Dienstplan"}}
function formatPeriod(period){const [year,month]=period.split("-").map(Number);return monthFormatter.format(new Date(Date.UTC(year,month-1,1)))}
function showWorkspace(){elements.login.hidden=true;elements.workspace.hidden=false;elements.forget.hidden=!localStorage.getItem("dienstplan-reader");loadPlans()}
function clearSessions(){readerToken="";adminToken="";sessionStorage.removeItem("dienstplan-reader");sessionStorage.removeItem("dienstplan-admin");localStorage.removeItem("dienstplan-reader")}
function renderPlans(){const query=elements.search.value.trim().toLocaleLowerCase("de"),filtered=plans.filter(plan=>`${plan.title} ${plan.period} ${formatPeriod(plan.period)}`.toLocaleLowerCase("de").includes(query));filtered.sort((a,b)=>elements.sort.value==="title"?a.title.localeCompare(b.title,"de"):elements.sort.value==="oldest"?a.period.localeCompare(b.period):b.period.localeCompare(a.period));elements.listStatus.textContent=`${filtered.length} von ${plans.length} Dienstplänen`;elements.plans.replaceChildren();if(!filtered.length){const empty=document.createElement("div");empty.className="empty";empty.textContent=query?"Keine passenden Dienstpläne gefunden.":"Noch keine Dienstpläne vorhanden.";elements.plans.append(empty);return}filtered.forEach(plan=>{const article=document.createElement("article");article.className="plan";const period=document.createElement("div");period.className="plan-month";const [year,month]=plan.period.split("-");period.innerHTML=`<span>${month}<strong>${year}</strong></span>`;const text=document.createElement("div"),title=document.createElement("h3"),meta=document.createElement("p");title.textContent=plan.title;meta.textContent=formatPeriod(plan.period);text.append(title,meta);const actions=document.createElement("div");actions.className="plan-actions";const open=document.createElement("button");open.type="button";open.textContent="Im Browser öffnen";open.addEventListener("click",()=>openPlan(plan));actions.append(open);if(adminToken){const remove=document.createElement("button");remove.type="button";remove.className="delete";remove.textContent="Löschen";remove.addEventListener("click",()=>deletePlan(plan));actions.append(remove)}article.append(period,text,actions);elements.plans.append(article)})}
async function loadPlans(){elements.listStatus.textContent="Dienstpläne werden geladen …";try{const result=await request("list");plans=result.plans||[];renderPlans()}catch(error){clearSessions();elements.workspace.hidden=true;elements.login.hidden=false;elements.loginStatus.textContent=error.message}}
async function openPlan(plan){elements.listStatus.textContent="PDF wird vorbereitet …";try{const result=await request("view",{path:plan.path});elements.viewerTitle.textContent=plan.title;elements.pdfViewer.src=`${result.url}#toolbar=1&navpanes=0&view=FitH`;elements.viewerDialog.showModal();elements.listStatus.textContent=""}catch(error){elements.listStatus.textContent=error.message}}
async function deletePlan(plan){if(!confirm(`„${plan.title}“ wirklich löschen?`))return;elements.listStatus.textContent="Dienstplan wird gelöscht …";try{await request("delete",{path:plan.path},adminToken);plans=plans.filter(item=>item.path!==plan.path);renderPlans()}catch(error){elements.listStatus.textContent=error.message}}

elements.loginForm.addEventListener("submit",async event=>{event.preventDefault();elements.loginStatus.textContent="Zugang wird geprüft …";try{const result=await request("login",{role:"reader",password:elements.password.value,remember:elements.remember.checked},"");readerToken=result.token;(elements.remember.checked?localStorage:sessionStorage).setItem("dienstplan-reader",readerToken);elements.password.value="";elements.remember.checked=false;elements.loginStatus.textContent="";showWorkspace()}catch(error){elements.loginStatus.textContent=error.message;elements.password.select()}});
elements.adminLoginForm.addEventListener("submit",async event=>{event.preventDefault();elements.adminLoginStatus.textContent="Administratorzugang wird geprüft …";try{const result=await request("login",{role:"admin",password:elements.adminPassword.value},"");adminToken=result.token;sessionStorage.setItem("dienstplan-admin",adminToken);elements.adminPassword.value="";elements.adminLoginStatus.textContent="";elements.adminDialog.close();elements.uploadDialog.showModal();renderPlans()}catch(error){elements.adminLoginStatus.textContent=error.message;elements.adminPassword.select()}});
elements.uploadForm.addEventListener("submit",async event=>{event.preventDefault();const file=elements.planFile.files[0];if(!file)return;if(file.type!=="application/pdf"&&!file.name.toLocaleLowerCase().endsWith(".pdf")){elements.uploadStatus.textContent="Bitte eine PDF-Datei auswählen.";return}if(file.size>20*1024*1024){elements.uploadStatus.textContent="Die PDF darf höchstens 20 MB groß sein.";return}elements.uploadStatus.textContent="Upload wird vorbereitet …";try{const signed=await request("upload-url",{title:elements.planTitle.value.trim(),period:elements.planMonth.value},adminToken);const {error}=await supabaseClient.storage.from(config.bucket).uploadToSignedUrl(signed.path,signed.token,file,{contentType:"application/pdf"});if(error)throw error;elements.uploadStatus.textContent="Dienstplan wurde bereitgestellt.";elements.uploadForm.reset();await loadPlans();setTimeout(()=>closeDialog(elements.uploadDialog),500)}catch(error){elements.uploadStatus.textContent=error.message}});
elements.openAdmin.addEventListener("click",()=>{if(adminToken){elements.uploadDialog.showModal();return}elements.adminLoginStatus.textContent="";elements.adminDialog.showModal();elements.adminPassword.focus()});elements.togglePassword.addEventListener("click",()=>toggle(elements.password,elements.togglePassword));elements.toggleAdminPassword.addEventListener("click",()=>toggle(elements.adminPassword,elements.toggleAdminPassword));elements.search.addEventListener("input",renderPlans);elements.sort.addEventListener("change",renderPlans);elements.logout.addEventListener("click",()=>{readerToken="";adminToken="";sessionStorage.removeItem("dienstplan-reader");sessionStorage.removeItem("dienstplan-admin");elements.workspace.hidden=true;elements.login.hidden=false;elements.password.focus()});elements.forget.addEventListener("click",()=>{localStorage.removeItem("dienstplan-reader");elements.forget.hidden=true});document.querySelectorAll("[data-close]").forEach(button=>button.addEventListener("click",()=>closeDialog(document.getElementById(button.dataset.close))));[elements.adminDialog,elements.uploadDialog,elements.viewerDialog].forEach(dialog=>dialog.addEventListener("click",event=>{if(event.target===dialog)closeDialog(dialog)}));
if(readerToken)showWorkspace();
