const $=selector=>document.querySelector(selector),config=window.DIENSTPLAN_CONFIG,supabaseClient=window.supabase.createClient(config.supabaseUrl,config.publishableKey),apiUrl=`${config.supabaseUrl}/functions/v1/${config.functionName}`;
const elements={login:$("#login"),loginForm:$("#login-form"),password:$("#password"),togglePassword:$("#toggle-password"),remember:$("#remember"),loginStatus:$("#login-status"),workspace:$("#workspace"),plans:$("#plans"),listStatus:$("#list-status"),search:$("#search"),sort:$("#sort"),logout:$("#logout"),forget:$("#forget"),openAdmin:$("#open-admin"),adminDialog:$("#admin-dialog"),adminLoginForm:$("#admin-login-form"),adminPassword:$("#admin-password"),toggleAdminPassword:$("#toggle-admin-password"),adminLoginStatus:$("#admin-login-status"),uploadDialog:$("#upload-dialog"),uploadForm:$("#upload-form"),planTitle:$("#plan-title"),planMonth:$("#plan-month"),planYear:$("#plan-year"),planFile:$("#plan-file"),rotatePdf:$("#rotate-pdf"),uploadStatus:$("#upload-status"),viewerDialog:$("#viewer-dialog"),viewerTitle:$("#viewer-title"),viewerStatus:$("#viewer-status"),pdfViewer:$("#pdf-viewer"),rotateLeft:$("#rotate-left"),rotateRight:$("#rotate-right")};
let plans=[],readerToken=sessionStorage.getItem("dienstplan-reader")||localStorage.getItem("dienstplan-reader")||"",adminToken=sessionStorage.getItem("dienstplan-admin")||"";
let viewerGeneration=0,currentPdfDocument=null,viewerRotation=0;
const monthFormatter=new Intl.DateTimeFormat("de-DE",{month:"long",year:"numeric",timeZone:"UTC"});

async function request(action,body={},token=readerToken){const response=await fetch(apiUrl,{method:"POST",headers:{"Content-Type":"application/json",apikey:config.publishableKey,...(token?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify({action,...body})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||"Die Anfrage konnte nicht ausgeführt werden.");return data}
function toggle(input,button){const visible=input.type==="text";input.type=visible?"password":"text";button.textContent=visible?"Anzeigen":"Ausblenden"}
function closeDialog(dialog){if(dialog.open)dialog.close();if(dialog===elements.viewerDialog){viewerGeneration++;currentPdfDocument=null;viewerRotation=0;elements.pdfViewer.replaceChildren();elements.viewerTitle.textContent="Dienstplan";elements.viewerStatus.textContent=""}}
function formatPeriod(period){const [year,month]=period.split("-").map(Number);return monthFormatter.format(new Date(Date.UTC(year,month-1,1)))}
function showWorkspace(){elements.login.hidden=true;elements.workspace.hidden=false;elements.forget.hidden=!localStorage.getItem("dienstplan-reader");loadPlans()}
function clearSessions(){readerToken="";adminToken="";sessionStorage.removeItem("dienstplan-reader");sessionStorage.removeItem("dienstplan-admin");localStorage.removeItem("dienstplan-reader")}
function renderPlans(){const query=elements.search.value.trim().toLocaleLowerCase("de"),filtered=plans.filter(plan=>`${plan.title} ${plan.period} ${formatPeriod(plan.period)}`.toLocaleLowerCase("de").includes(query));filtered.sort((a,b)=>elements.sort.value==="title"?a.title.localeCompare(b.title,"de"):elements.sort.value==="oldest"?a.period.localeCompare(b.period):b.period.localeCompare(a.period));elements.listStatus.textContent=`${filtered.length} von ${plans.length} Dienstplänen`;elements.plans.replaceChildren();if(!filtered.length){const empty=document.createElement("div");empty.className="empty";empty.textContent=query?"Keine passenden Dienstpläne gefunden.":"Noch keine Dienstpläne vorhanden.";elements.plans.append(empty);return}filtered.forEach(plan=>{const article=document.createElement("article");article.className="plan";const period=document.createElement("div");period.className="plan-month";const [year,month]=plan.period.split("-");period.innerHTML=`<span>${month}<strong>${year}</strong></span>`;const text=document.createElement("div"),title=document.createElement("h3"),meta=document.createElement("p");title.textContent=plan.title;meta.textContent=formatPeriod(plan.period);text.append(title,meta);const actions=document.createElement("div");actions.className="plan-actions";const open=document.createElement("button");open.type="button";open.textContent="Im Browser öffnen";open.addEventListener("click",()=>openPlan(plan));actions.append(open);if(adminToken){const remove=document.createElement("button");remove.type="button";remove.className="delete";remove.textContent="Löschen";remove.addEventListener("click",()=>deletePlan(plan));actions.append(remove)}article.append(period,text,actions);elements.plans.append(article)})}
async function loadPlans(){elements.listStatus.textContent="Dienstpläne werden geladen …";try{const result=await request("list");plans=result.plans||[];renderPlans()}catch(error){clearSessions();elements.workspace.hidden=true;elements.login.hidden=false;elements.loginStatus.textContent=error.message}}
async function renderCurrentPdf(){if(!currentPdfDocument)return;const generation=++viewerGeneration,pdfDocument=currentPdfDocument,scrollTop=elements.pdfViewer.scrollTop;elements.pdfViewer.replaceChildren();elements.viewerStatus.textContent=`${pdfDocument.numPages} ${pdfDocument.numPages===1?"Seite":"Seiten"} · Drehung ${viewerRotation}°`;for(let number=1;number<=pdfDocument.numPages;number++){if(generation!==viewerGeneration)return;const page=await pdfDocument.getPage(number),availableWidth=Math.min(elements.pdfViewer.clientWidth-28,1200),baseViewport=page.getViewport({scale:1,rotation:page.rotate+viewerRotation}),scale=Math.max(.5,availableWidth/baseViewport.width),viewport=page.getViewport({scale,rotation:page.rotate+viewerRotation}),sheet=document.createElement("section"),label=document.createElement("p"),canvas=document.createElement("canvas"),context=canvas.getContext("2d");sheet.className="pdf-page";label.textContent=`Seite ${number} von ${pdfDocument.numPages}`;canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);canvas.style.width=`${Math.round(viewport.width)}px`;canvas.style.height=`${Math.round(viewport.height)}px`;sheet.append(label,canvas);elements.pdfViewer.append(sheet);await page.render({canvasContext:context,viewport}).promise}elements.pdfViewer.scrollTop=scrollTop}
async function openPlan(plan){elements.listStatus.textContent="PDF wird vorbereitet …";try{if(!window.pdfjsLib)throw new Error("Die PDF-Ansicht konnte nicht geladen werden.");window.pdfjsLib.GlobalWorkerOptions.workerSrc="https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/pdf.worker.min.js";const result=await request("view",{path:plan.path}),generation=++viewerGeneration;elements.viewerTitle.textContent=plan.title;elements.viewerStatus.textContent="PDF wird geladen …";elements.pdfViewer.replaceChildren();elements.viewerDialog.showModal();const pdfDocument=await window.pdfjsLib.getDocument(result.url).promise;if(generation!==viewerGeneration)return;currentPdfDocument=pdfDocument;viewerRotation=0;await renderCurrentPdf();elements.listStatus.textContent=""}catch(error){closeDialog(elements.viewerDialog);elements.listStatus.textContent=error.message}}
async function deletePlan(plan){if(!confirm(`„${plan.title}“ wirklich löschen?`))return;elements.listStatus.textContent="Dienstplan wird gelöscht …";try{await request("delete",{path:plan.path},adminToken);plans=plans.filter(item=>item.path!==plan.path);renderPlans()}catch(error){elements.listStatus.textContent=error.message}}
async function preparePdf(file){if(!elements.rotatePdf.checked)return file;if(!window.PDFLib)throw new Error("Die PDF-Drehung konnte nicht geladen werden.");elements.uploadStatus.textContent="PDF wird um 90° nach rechts gedreht …";const document=await window.PDFLib.PDFDocument.load(await file.arrayBuffer());document.getPages().forEach(page=>page.setRotation(window.PDFLib.degrees((page.getRotation().angle+90)%360)));const bytes=await document.save();return new Blob([bytes],{type:"application/pdf"})}

elements.loginForm.addEventListener("submit",async event=>{event.preventDefault();elements.loginStatus.textContent="Zugang wird geprüft …";try{const result=await request("login",{role:"reader",password:elements.password.value,remember:elements.remember.checked},"");readerToken=result.token;(elements.remember.checked?localStorage:sessionStorage).setItem("dienstplan-reader",readerToken);elements.password.value="";elements.remember.checked=false;elements.loginStatus.textContent="";showWorkspace()}catch(error){elements.loginStatus.textContent=error.message;elements.password.select()}});
elements.adminLoginForm.addEventListener("submit",async event=>{event.preventDefault();elements.adminLoginStatus.textContent="Administratorzugang wird geprüft …";try{const result=await request("login",{role:"admin",password:elements.adminPassword.value},"");adminToken=result.token;sessionStorage.setItem("dienstplan-admin",adminToken);elements.adminPassword.value="";elements.adminLoginStatus.textContent="";elements.adminDialog.close();elements.uploadDialog.showModal();renderPlans()}catch(error){elements.adminLoginStatus.textContent=error.message;elements.adminPassword.select()}});
elements.uploadForm.addEventListener("submit",async event=>{event.preventDefault();const file=elements.planFile.files[0];if(!file)return;if(file.type!=="application/pdf"&&!file.name.toLocaleLowerCase().endsWith(".pdf")){elements.uploadStatus.textContent="Bitte eine PDF-Datei auswählen.";return}if(file.size>20*1024*1024){elements.uploadStatus.textContent="Die PDF darf höchstens 20 MB groß sein.";return}elements.uploadStatus.textContent="Upload wird vorbereitet …";try{const uploadFile=await preparePdf(file);if(uploadFile.size>20*1024*1024)throw new Error("Die gedrehte PDF überschreitet 20 MB.");const period=`${elements.planYear.value}-${elements.planMonth.value}`,signed=await request("upload-url",{title:elements.planTitle.value.trim(),period},adminToken);const {error}=await supabaseClient.storage.from(config.bucket).uploadToSignedUrl(signed.path,signed.token,uploadFile,{contentType:"application/pdf"});if(error)throw error;elements.uploadStatus.textContent="Dienstplan wurde bereitgestellt.";elements.uploadForm.reset();elements.rotatePdf.checked=true;setPeriodDefaults();await loadPlans();setTimeout(()=>closeDialog(elements.uploadDialog),500)}catch(error){elements.uploadStatus.textContent=error.message}});
elements.openAdmin.addEventListener("click",()=>{if(adminToken){elements.uploadDialog.showModal();return}elements.adminLoginStatus.textContent="";elements.adminDialog.showModal();elements.adminPassword.focus()});elements.togglePassword.addEventListener("click",()=>toggle(elements.password,elements.togglePassword));elements.toggleAdminPassword.addEventListener("click",()=>toggle(elements.adminPassword,elements.toggleAdminPassword));elements.rotateLeft.addEventListener("click",()=>{viewerRotation=(viewerRotation+270)%360;renderCurrentPdf()});elements.rotateRight.addEventListener("click",()=>{viewerRotation=(viewerRotation+90)%360;renderCurrentPdf()});elements.search.addEventListener("input",renderPlans);elements.sort.addEventListener("change",renderPlans);elements.logout.addEventListener("click",()=>{readerToken="";adminToken="";sessionStorage.removeItem("dienstplan-reader");sessionStorage.removeItem("dienstplan-admin");elements.workspace.hidden=true;elements.login.hidden=false;elements.password.focus()});elements.forget.addEventListener("click",()=>{localStorage.removeItem("dienstplan-reader");elements.forget.hidden=true});document.querySelectorAll("[data-close]").forEach(button=>button.addEventListener("click",()=>closeDialog(document.getElementById(button.dataset.close))));[elements.adminDialog,elements.uploadDialog,elements.viewerDialog].forEach(dialog=>dialog.addEventListener("click",event=>{if(event.target===dialog)closeDialog(dialog)}));
function setPeriodDefaults(){const now=new Date(),year=now.getFullYear();elements.planYear.replaceChildren();for(let value=year-1;value<=year+3;value++){const option=document.createElement("option");option.value=String(value);option.textContent=String(value);elements.planYear.append(option)}elements.planYear.value=String(year);elements.planMonth.value=String(now.getMonth()+1).padStart(2,"0")}
setPeriodDefaults();if(readerToken)showWorkspace();
