'use strict';
const API='https://tjjtemvclcgqmuhlnumr.supabase.co/functions/v1/haema-morphology';
const root=document.querySelector('#app'),logout=document.querySelector('#logout');
let content=null,quiz=[],qi=0,score=0,answered=false,touchX=0;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const token=()=>localStorage.getItem('hm_token')||sessionStorage.getItem('hm_token')||'';
async function api(action,{method='GET',body}={}){const r=await fetch(API+'?action='+action,{method,headers:{'Content-Type':'application/json','Authorization':'Bearer '+token()},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw new Error(d.error||'Anfrage fehlgeschlagen');return d}
function nav(active){return '<nav class="nav">'+[['home','Start'],['knowledge','Wissensbasis'],['atlas','Zellatlas'],['quiz','Quick Swipe']].map(([id,label])=>'<button data-nav="'+id+'" class="'+(active===id?'active':'')+'">'+label+'</button>').join('')+'</nav>'}
function bindNav(){document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>render(b.dataset.nav))}
async function load(){content=await api('home');render('home')}
function sequence(){return '<div class="sequence">'+content.cells.map(c=>'<div class="mini">'+c.svg+'<b>'+esc(c.name.replace(' neutrophiler Granulozyt',''))+'</b></div>').join('')+'</div>'}
function render(v){logout.hidden=false;if(v==='home')home();if(v==='knowledge')knowledge();if(v==='atlas')atlas();if(v==='quiz')startQuiz();bindNav();window.scrollTo({top:0,behavior:'smooth'})}
function home(){root.innerHTML='<section class="hero"><div class="eyebrow">Hämatologie Trainer · Zytomorphologie</div><h1>Sehen lernen.<br><span class="rose">Begriffe verankern.</span></h1><p class="lead">Ein schneller Wiedereinstieg in die hämatologische Zytomorphologie – mit deutscher Befundsprache, schematischen Zellen und kurzen Wiederholungen.</p></section>'+nav('home')+'<div class="grid"><article class="card"><div class="eyebrow">Wissensbasis</div><h2>Vom Beschreiben zum Befunden</h2><p>Feste Terminologie, Reifungslogik und die wichtigsten morphologischen Übergänge.</p><button class="primary" data-nav="knowledge">Wissensbasis öffnen</button></article><article class="card"><div class="eyebrow">2 Minuten</div><h2>Quick Swipe</h2><p>Sechs schematische Zellen erkennen, direkt auflösen und schwierige Übergänge wiederholen.</p><button class="primary" data-nav="quiz">Runde starten</button></article></div>'+sequence()}
function knowledge(){root.innerHTML=nav('knowledge')+'<div class="eyebrow">Wissensdatenbank</div><h1>Zytomorphologie systematisch neu einsteigen</h1><p class="lead">Die ersten Module bilden die neutrophile Granulopoese ab. Weitere Zellreihen können im selben Format ergänzt werden.</p>'+content.lessons.map(l=>'<article class="lesson"><div class="eyebrow">'+esc(l.subtitle)+'</div><h2>'+esc(l.title)+'</h2><p class="lead">'+esc(l.lead)+'</p>'+l.sections.map(s=>'<h3>'+esc(s[0])+'</h3><p>'+esc(s[1])+'</p>').join('')+(l.id==='granulopoiesis'?sequence():'')+'<div class="sources"><b>Referenzen</b>'+l.sources.map(s=>'<a href="'+esc(s.url)+'" target="_blank" rel="noopener noreferrer">'+esc(s.title)+' ↗</a>').join('')+'</div></article>').join('')}
function atlas(){root.innerHTML=nav('atlas')+'<div class="eyebrow">Zellatlas · neutrophile Reihe</div><h1>Sechs Stufen, drei Veränderungen</h1><p class="lead">Achte parallel auf Chromatin, Granulation und Kernform. Die Zeichnungen sind bewusst schematisch und ersetzen keine realen Ausstrichbilder.</p><div class="atlas">'+content.cells.map(c=>'<article class="card"><div class="figure">'+c.svg+'</div><h2>'+esc(c.name)+'</h2><small>'+esc(c.en)+' · '+esc(c.size)+'</small><div class="facts"><div class="fact"><b>Kern</b>'+esc(c.nucleus)+'</div><div class="fact"><b>Chromatin</b>'+esc(c.chromatin)+'</div><div class="fact"><b>Nukleolen</b>'+esc(c.nucleoli)+'</div><div class="fact"><b>Granula</b>'+esc(c.granules)+'</div></div><div class="distinction"><b>Abgrenzung:</b> '+esc(c.distinction)+'</div></article>').join('')+'</div>'}
async function startQuiz(){try{quiz=await api('quiz');qi=0;score=0;showQ()}catch(e){root.innerHTML=nav('quiz')+'<div class="card quiz"><p class="error">'+esc(e.message)+'</p></div>';bindNav()}}
function showQ(){const q=quiz[qi];root.innerHTML=nav('quiz')+'<div class="quiz"><div class="quiz-top"><span>Quick Swipe · Granulopoese</span><b>'+(qi+1)+' / '+quiz.length+'</b></div><div class="progress"><i style="width:'+(qi/quiz.length*100)+'%"></i></div><article class="card" id="quizCard"><div class="figure">'+q.svg+'</div><h2>'+esc(q.prompt)+'</h2><div class="options">'+q.options.map(o=>'<button class="option" data-answer="'+esc(o.value)+'">'+esc(o.label)+'</button>').join('')+'</div><div id="fb"></div><div class="actions"><button id="next" class="primary" hidden>'+(qi===quiz.length-1?'Ergebnis':'Weiter →')+'</button></div></article></div>';bindNav();answered=false;document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>answer(q.id,b.dataset.answer));const card=document.querySelector('#quizCard');card.addEventListener('touchstart',e=>touchX=e.touches[0].clientX,{passive:true});card.addEventListener('touchend',e=>{if(answered&&e.changedTouches[0].clientX-touchX<-60)next()},{passive:true})}
async function answer(id,value){if(answered)return;answered=true;try{const r=await api('answer',{method:'POST',body:{id,value}});if(r.isCorrect)score++;document.querySelectorAll('[data-answer]').forEach(b=>{b.disabled=true;b.classList.toggle('correct',b.dataset.answer===r.correct);b.classList.toggle('wrong',b.dataset.answer===value&&!r.isCorrect)});document.querySelector('#fb').innerHTML='<div class="feedback">'+(r.isCorrect?'<b>Richtig.</b> ':'<b>Richtig ist '+esc(r.correctLabel)+'.</b> ')+esc(r.explanation)+'</div>';const n=document.querySelector('#next');n.hidden=false;n.onclick=next}catch(e){answered=false;document.querySelector('#fb').innerHTML='<p class="error">'+esc(e.message)+'</p>'}}
function next(){if(qi===quiz.length-1)return result();qi++;showQ();window.scrollTo({top:0,behavior:'smooth'})}
function result(){root.innerHTML=nav('quiz')+'<div class="card quiz"><div class="eyebrow">Runde abgeschlossen</div><h1>'+score+' / '+quiz.length+'</h1><p class="lead">Die schematischen Karten sind die erste Ebene. Als nächstes kommen reale Bildfälle mit derselben Befundsprache.</p><div class="actions"><button class="quiet" id="toAtlas">Zellatlas</button><button class="primary" id="again">Noch einmal</button></div></div>';bindNav();document.querySelector('#again').onclick=startQuiz;document.querySelector('#toAtlas').onclick=()=>render('atlas')}
function login(){logout.hidden=true;root.innerHTML='<form class="login" id="loginForm"><div class="eyebrow">Geschützter Lernbereich</div><h1>Zytomorphologie</h1><p>Wissensbasis, Zellatlas und Quick-Swipe-Trainer.</p><label for="pw">Passwort</label><input id="pw" type="password" autocomplete="current-password" required><label><input id="remember" type="checkbox"> Auf diesem Gerät angemeldet bleiben</label><p id="err" class="error"></p><button class="primary" type="submit">Öffnen</button></form>';document.querySelector('#loginForm').onsubmit=async e=>{e.preventDefault();const btn=e.target.querySelector('button');btn.disabled=true;document.querySelector('#err').textContent='';try{const r=await fetch(API+'?action=login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:document.querySelector('#pw').value,remember:document.querySelector('#remember').checked})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Anmeldung fehlgeschlagen');(document.querySelector('#remember').checked?localStorage:sessionStorage).setItem('hm_token',d.token);await load()}catch(e){document.querySelector('#err').textContent=e.message}finally{btn.disabled=false}}}
logout.onclick=()=>{localStorage.removeItem('hm_token');sessionStorage.removeItem('hm_token');login()};
if(token())load().catch(()=>login());else login();